### ISSUE TITLE
Handle invalid pid

### ISSUE THREAD

**Issue by yogeswaran** [poise/poise-service#34] opened 2016-10-14 13:34 UTC
When a machine crashes or the service dies for any reason, the pid file contains an invalid pid, ie either there is no process with that pid or the pid rolled and some other process owns that pid now. 

In this case, _stop() function tries to send "kill -0" to the process and fails. Since the stop fails, restart action also fails and the service never come up.

Invalid pid need to be handled better.

here is the stop function - https://github.com/poise/poise-service/blob/0d04e7df5734c5c703d0e2f12aab90f55380c268/chef/templates/default/sysvinit.sh.erb#L64-L70

**Comment by shalstea** [comment] 2016-10-14 13:40
For example if kill -0 fails it could check the name of the executable and if it doesn't match, it could remove the pid file and try again, in this case doing a start.

**Comment by coderanger** [comment] 2016-10-18 18:39
Closing this out as it is not a bug. It's an inherent limitation in init.d-style service management. Fortunately this can only come up when PIDs loop around so the previous PID in the file is re-used for a new process, which takes a while. Other providers detect process failures fast enough that this isn't an issue (and don't use PID file tracking anyway for the most part).

**Closed by coderanger** 2016-10-18 18:39 UTC
