### ISSUE TITLE
undefined method `reload_shim' for PoiseService::Resources::PoiseService::Resource

### ISSUE THREAD

**Issue by gretel** [poise/poise-service#15] opened 2015-12-16 13:29 UTC
following the doc i stumbled into an issue:

```
  poise_service 'srv' do
    command 'somecmd'
    user 'someuser'
    directory '/somedir''
    provider :upstart
    reload_shim true
    stop_signal 'KILL'
  end
```
`chef 12.5.1` running on `ubuntu 12.04` including `upstart 1.5`. regards

**Comment by coderanger** [comment] 2015-12-16 18:38
Duplicate of #16.

**Closed by coderanger** 2015-12-16 18:38 UTC
